### ISSUE TITLE
Add a script to uninstall the extension

### ISSUE THREAD

**Issue by MrDvorak** [MrDvorak/layout-hotkeys#1]
### To-Do:
- [ ] Implement uninstall.sh to fully remove the extension installed by install.sh.
- [ ] Add a force installation flag to install.sh for uninstalling the extension before further installation.
- [ ] Move the scripts to the tool directory and update README.md respectfully.
